trigger:
  - dev

jobs:
- job: WebApp
  displayName: 'DotNet-Web-APP-CI'
  pool:
    name: Azure Pipelines
    vmImage: 'ubuntu-18.04'
    demands: java
  variables:
    BuildConfiguration: release

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/WebApp.csproj'

- task: PowerShell@2
  displayName: 'PS: Add project GUID'
  inputs:
    targetType: filePath
    filePath: './sonar-add-project-guid.ps1'
    workingDirectory: WebApp

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'my-sonarcloud-azdevops-connection'
    organization: ashikkhulal
    projectKey: 'dotnet-core-web-app'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

